"""
Django settings for settings project.

Generated by 'django-admin startproject' using Django 3.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from pathlib import Path

from dotenv import load_dotenv
from split_settings.tools import include

load_dotenv(dotenv_path=Path(__file__).resolve().parent.parent.parent.joinpath(".env"))

include(
    "components/database.py",
    "components/security.py",
    "components/app.py",
    "components/password_validators.py",
    "components/localization.py",
    "components/static.py",
    "components/logging.py",
)
