# Generated by Django 3.2.16 on 2022-10-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_auto_20221011_1746"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personfilmwork",
            name="role",
            field=models.CharField(
                choices=[("actor", "actor"), ("writer", "writer"), ("director", "director")],
                max_length=10,
                verbose_name="role",
            ),
        ),
    ]
