# Generated by Django 4.1.3 on 2022-11-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_filmwork_film_work_updated_at_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmwork",
            name="age_limit",
            field=models.CharField(
                choices=[("G", "G"), ("PG", "PG"), ("PG-13", "PG-13"), ("NC-17 ", "NC-17 ")],
                max_length=7,
                null=True,
                verbose_name="age_limit",
            ),
        ),
    ]
