"""03_add_user_oauth_account

Revision ID: bb9ec5b4d683
Revises: 81388bb6e0d9
Create Date: 2023-01-24 11:27:46.098085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "bb9ec5b4d683"
down_revision = "81388bb6e0d9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_oauth_account",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("oauth_provider_name", postgresql.ENUM("google", "yandex", name="oauthproviderenum"), nullable=False),
        sa.Column("oauth_account_id", sa.String(length=60), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_provider_account"), "user_oauth_account", ["oauth_provider_name", "oauth_account_id"], unique=True
    )
    op.create_index(op.f("ix_user_provider"), "user_oauth_account", ["user_id", "oauth_provider_name"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_provider"), table_name="user_oauth_account")
    op.drop_index(op.f("ix_provider_account"), table_name="user_oauth_account")
    op.drop_table("user_oauth_account")
    # ### end Alembic commands ###
